### ISSUE TITLE
Should this be a `cg-*` repository?

### ISSUE THREAD

**Issue by rogeruiz** [18F/coming-attractions#3]
Since this is mainly for cloud foundry, ie. :cloud:.gov, should this be renamed to `cg-coming-attractions`? It didn't seem like it should since I'd rather this live under the tenants responsibility but I also didn't feel :100: about making that decision _all by myself_. So let's discuss it in this issue. 🎉

**Comment by afeld** [comment]
Since it isn't 18F/cloud.gov-specific, I'd keep the name, and transfer it to @cloudfoundry-community 🙂

**Comment by rogeruiz** [comment]
Good idea. I think @hollyallen mentioned that we might want to offer something like this to ☁️.gov tenants, but we could always manage that in the future. Especially if it gets transferred to @cloudfoundry-community. Yay to less forks and less repos 🎉. Closing this for now.
